package main

import (
	"encoding/json"
	"strings"
	"testing"
)

const sample = `
en:
  pito:
    copy:
      thinking:
        slash:
          doing:
            - "Executing"
            - "Overclocking"
            - "Crunching"
          done:
            - "Executed"
            - "Overclocked"
            - "Crunched"
        confirmation:
          doing:
            - "Weighing"
          done:
            - "Weighed"
        not_a_pool:
          resolved: "%{word} for %{elapsed}s"
      tui:
        clipboard:
          - "Yoinked to your clipboard."
          - "Copied. No takebacks."
      start_screen:
        tips:
          - "Type /help when you inevitably forget everything."
`

const paletteSample = `
en:
  pito:
    palette:
      ctrl_k:
        title: "Commands"
        esc_hint: "Esc"
        search_placeholder: "Search"
        sections:
          general: "General"
        commands:
          help: "Show command reference"
`

const shellSample = `
en:
  pito:
    shell:
      chatbox:
        filter:
          channel_shortcut: "shift+tab"
          period_shortcut: "shift+space"
        no_channels: "none"
`

func TestExtractKeepsSourceOrderAndSkipsNonPools(t *testing.T) {
	snap, err := extract([]byte(sample), "config/locales/pito/copy/en.yml")
	if err != nil {
		t.Fatal(err)
	}
	slash, ok := snap.Dictionaries["slash"]
	if !ok {
		t.Fatalf("slash dictionary missing: %#v", snap.Dictionaries)
	}
	// ORDER is load-bearing (payload order/word_index index into these).
	want := []string{"Executing", "Overclocking", "Crunching"}
	for i, w := range want {
		if slash.Doing[i] != w {
			t.Fatalf("doing[%d] = %q, want %q", i, slash.Doing[i], w)
		}
	}
	if slash.Done[2] != "Crunched" {
		t.Fatalf("done[2] = %q", slash.Done[2])
	}
	if _, ok := snap.Dictionaries["not_a_pool"]; ok {
		t.Fatal("entries without a doing pool must be skipped")
	}
	if len(snap.Dictionaries) != 2 {
		t.Fatalf("want 2 dictionaries, got %d", len(snap.Dictionaries))
	}
	if len(snap.Clipboard) != 2 || snap.Clipboard[0] != "Yoinked to your clipboard." {
		t.Fatalf("clipboard pool wrong: %#v", snap.Clipboard)
	}
	if len(snap.StartScreen.Tips) != 1 || !strings.Contains(snap.StartScreen.Tips[0], "/help") {
		t.Fatalf("tips pool wrong: %#v", snap.StartScreen.Tips)
	}
}

func TestExtractPaletteAndShell(t *testing.T) {
	pal := extractPalette([]byte(paletteSample))
	if pal.Title != "Commands" || pal.Sections["general"] != "General" ||
		pal.Commands["help"] != "Show command reference" {
		t.Fatalf("palette wrong: %#v", pal)
	}
	sh := extractShell([]byte(shellSample))
	if sh.ChannelShortcut != "shift+tab" || sh.PeriodShortcut != "shift+space" || sh.NoChannels != "none" {
		t.Fatalf("shell wrong: %#v", sh)
	}
	// Absent subtrees degrade to zero values, never error.
	if got := extractPalette([]byte("en: {}" + "\n")); got.Title != "" || len(got.Commands) != 0 {
		t.Fatalf("missing palette must degrade: %#v", got)
	}
}

func TestExtractClipboardOptional(t *testing.T) {
	// An older pito ref without pito.copy.tui degrades to an empty pool.
	no := "en:\n  pito:\n    copy:\n      thinking:\n        slash:\n          doing:\n            - \"Executing\"\n"
	snap, err := extract([]byte(no), "x")
	if err != nil {
		t.Fatal(err)
	}
	if len(snap.Clipboard) != 0 {
		t.Fatalf("want empty clipboard pool, got %#v", snap.Clipboard)
	}
}

func TestExtractMissingSubtreeErrors(t *testing.T) {
	if _, err := extract([]byte("en:\n  pito: {}\n"), "x"); err == nil {
		t.Fatal("want error for missing copy.thinking subtree")
	}
}

func TestMarshalDeterministic(t *testing.T) {
	snap, err := extract([]byte(sample), "config/locales/pito/copy/en.yml")
	if err != nil {
		t.Fatal(err)
	}
	a, err := marshal(snap)
	if err != nil {
		t.Fatal(err)
	}
	b, _ := marshal(snap)
	if string(a) != string(b) {
		t.Fatal("marshal must be deterministic")
	}
	var round snapshot
	if err := json.Unmarshal(a, &round); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(a), "generated by tools/copygen") {
		t.Fatal("source note missing")
	}
}
